name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  firebase_storage: ^12.4.9
  animated_snack_bar: ^0.4.0
  intl: ^0.20.2
  cloud_firestore: ^5.6.11
  get: ^4.6.5
  modal_bottom_sheet: ^3.0.0-pre
  rut_utils: ^0.1.2
  spelling_number: ^0.0.4
  dropdown_button2: ^2.3.9
  flutter_holo_date_picker: ^2.0.0
  responsive_grid_list: ^1.4.0
  group_button: ^5.3.3
  pdf: ^3.10.4
  printing: ^5.14.2
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  image_editor_plus: ^1.0.4
  image_cropper: ^9.1.0
  google_mlkit_document_scanner: ^0.4.0
  date_picker_timeline: ^1.2.3
  share_plus: ^10.0.2
  file_saver: ^0.2.12
  open_filex: ^4.5.0
  calendar_date_picker2: ^2.0.1

  # Dependencia oficial de localizaciones (del SDK)
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

dependency_overrides:
  screenshot: ^3.0.0 # Force screenshot to version 3.0.0 or higher

flutter:
  uses-material-design: true
  
  assets:
    - lib/images/

  fonts:
    - family: Calibri
      fonts:
        - asset: lib/images/Calibri Regular.ttf
    - family: Calibri Bold
      fonts:
        - asset: lib/images/Calibri Bold.ttf
    - family: Cambria
      fonts:
        - asset: lib/images/Cambria.ttf