// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW0ev0i40wKKjb0slIa6D-sTu_QFFZmNw',
    appId: '1:233057701817:web:26a75cb2d96783f8cf7068',
    messagingSenderId: '233057701817',
    projectId: 'contratos-control',
    authDomain: 'contratos-control.firebaseapp.com',
    storageBucket: 'contratos-control.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCshva9axWGAMQ78nFnf9ZUcnKcraR2wow',
    appId: '1:233057701817:android:658338bd7d1499d7cf7068',
    messagingSenderId: '233057701817',
    projectId: 'contratos-control',
    storageBucket: 'contratos-control.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW0ev0i40wKKjb0slIa6D-sTu_QFFZmNw',
    appId: '1:233057701817:web:49d0ddaafa3484fecf7068',
    messagingSenderId: '233057701817',
    projectId: 'contratos-control',
    authDomain: 'contratos-control.firebaseapp.com',
    storageBucket: 'contratos-control.appspot.com',
  );
}
